// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmvokAroraippRol6cTaeMBfVlbluwQo',
    appId: '1:388698899604:web:ae594da48732ee5153e081',
    messagingSenderId: '388698899604',
    projectId: 'websisutemu',
    authDomain: 'websisutemu.firebaseapp.com',
    storageBucket: 'websisutemu.firebasestorage.app',
    measurementId: 'G-2CNTR0MGSV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_z7FPZJxP_k3OgFjYV6rhmjMqrw_IfE',
    appId: '1:388698899604:ios:7955ff680960d00553e081',
    messagingSenderId: '388698899604',
    projectId: 'websisutemu',
    storageBucket: 'websisutemu.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_z7FPZJxP_k3OgFjYV6rhmjMqrw_IfE',
    appId: '1:388698899604:ios:7955ff680960d00553e081',
    messagingSenderId: '388698899604',
    projectId: 'websisutemu',
    storageBucket: 'websisutemu.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MVfPZtkkRan_ZdN54up-6FEMynuYDwE',
    appId: '1:388698899604:android:deaf07c6a8d8a43253e081',
    messagingSenderId: '388698899604',
    projectId: 'websisutemu',
    storageBucket: 'websisutemu.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmvokAroraippRol6cTaeMBfVlbluwQo',
    appId: '1:388698899604:web:ed729583d505daf253e081',
    messagingSenderId: '388698899604',
    projectId: 'websisutemu',
    authDomain: 'websisutemu.firebaseapp.com',
    storageBucket: 'websisutemu.firebasestorage.app',
    measurementId: 'G-R5XC4EMRNB',
  );

}